import { sidebar } from "vuepress-theme-hope";


export const zhSidebar = sidebar({
  "/en/": false,

  "/doc/": [
    {
      text: "快速了解",
      icon: "leibie",
      prefix: "info/",
      collapsible: true,
      children: [
        "功能介绍",
        "项目介绍",
        "架构介绍",
        "租户模式介绍",
        "3.x和4.x区别",
        "微服务版和单体版区别",
        "代码地址",
        "开发规范",
        "文档内容反馈",
        "视频软件下载",
      ],
    },
    {
      text: "快速启动",
      icon: "featuresNew",
      prefix: "start/",
      collapsible: true,
      link: "/doc/start/如何高效提问",
      children: [
        "如何高效提问",
        "服务介绍",
        "环境要求",
        "项目导入",
      ],
    },
  ],
});
// export const zhSidebar = sidebar({
//   "/en/": false,
//
//   "/guide/": [
//     "introduce",
//     {
//       text: "快速上手",
//       icon: "leibie",
//       prefix: "getstarted/",
//       collapsible: true,
//       children: [
//         "start",
//         "projectEnv",
//         "dataMapping",
//         "stringGenerationStrategy",
//         "icon",
//         "otherConfig",
//         "shortcut",
//       ],
//     },
//     "install",
//     {
//       text: "功能",
//       icon: "featuresNew",
//       prefix: "features/",
//       collapsible: true,
//       link: "/guide/features",
//       children: [
//         "makeIconMove",
//         "projectLevelDomainConfig",
//         "projectValueConfig",
//         "searchEveryWhere",
//         "apiGroup",
//         "debugApi",
//         "downloadApi",
//         "stopRequest",
//         "navigateCurrentMethod",
//         "saveRequest",
//         "tempRequest",
//         "regenerate",
//         "curlImport",
//         "copyCurl",
//         "copyUrl",
//         "apiDocSync",
//         "historyRequest",
//         "settingManager",
//         "fullScreen",
//         "annualReport",
//         "docAndContact",
//         "htmlPreview",
//         "swaggerDefaultValueParse",
//         "autoDescription",
//         "apiList",
//         "apiToPostman",
//         "apiImportExport",
//         "batchExportApiDoc",
//         "apiNavigateTree",
//         "apiPreview",
//         "apiCommentPreview",
//         "script",
//         "quickAddHeader",
//         "headerGroup",
//         "jsonGrammarCheck",
//       ],
//     },
//     "script",
//     "history",
//     "teamwork",
//     "buy",
//     "versionCompare",
//     "concatGroup",
//     "teachingVideo",
//     "faq",
//     "eula",
//     "priceAdjust",
//     "sponsorList",
//     "activity",
//     "link",
//     "whatsnew",
//     "feature",
//   ],
// });
